import { useState } from "react";
import { FlatList, Modal, Pressable, StyleSheet, Text, View } from "react-native";
import { BrandMark } from "@/components/brand-mark";
import { EntryCard } from "@/components/entry-card";
import { ScreenContainer } from "@/components/screen-container";
import { useCognitiveWorkspace } from "@/hooks/use-cognitive-workspace";
import { MirrorEntry } from "@/lib/cognitive";
import { modeMeta, t } from "@/lib/i18n";

export default function WorkspaceScreen() { const { state, deleteEntry } = useCognitiveWorkspace(); const [selected, setSelected] = useState<MirrorEntry | null>(null); const plans = state.entries.filter((entry) => entry.mode === "plan").length; const tx = (key: Parameters<typeof t>[1]) => t(state.language, key); return <ScreenContainer style={styles.screen}><FlatList data={state.entries} keyExtractor={(entry) => entry.id} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} renderItem={({ item }) => <EntryCard entry={item} onPress={() => setSelected(item)} />} ListHeaderComponent={<View><BrandMark compact /><Text style={styles.kicker}>{tx("privateSpace")}</Text><Text style={styles.title}>{tx("workspaceTitle")}</Text><Text style={styles.copy}>{tx("workspaceCopy")}</Text><View style={styles.metrics}><View style={styles.metric}><Text style={styles.number}>{state.entries.length}</Text><Text style={styles.metricLabel}>{tx("saved")}</Text></View><View style={styles.metric}><Text style={[styles.number, { color: "#69D6A3" }]}>{plans}</Text><Text style={styles.metricLabel}>{tx("humanePlans")}</Text></View></View><Text style={styles.section}>{tx("yourRecord")}</Text></View>} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyTitle}>{tx("nothingSaved")}</Text><Text style={styles.emptyCopy}>{tx("nothingSavedCopy")}</Text></View>} /><Modal transparent animationType="slide" visible={Boolean(selected)} onRequestClose={() => setSelected(null)}><View style={styles.backdrop}><View style={styles.sheet}><View style={styles.handle}/>{selected ? <><View style={styles.header}><View><Text style={[styles.mode, { color: modeMeta(state.language, selected.mode).accent }]}>{modeMeta(state.language, selected.mode).label}</Text><Text style={styles.sheetTitle}>{tx("entryReflection")}</Text></View><Pressable onPress={() => setSelected(null)} style={styles.close}><Text style={styles.closeText}>×</Text></Pressable></View><Text style={styles.thought}>{selected.thought}</Text><FlatList style={styles.answers} contentContainerStyle={styles.answerContent} data={selected.answers} keyExtractor={(item) => item.prompt} renderItem={({ item }) => <View style={styles.answer}><Text style={styles.prompt}>{item.prompt}</Text><Text style={styles.response}>{item.response || (state.language === "bn" ? "কোনো উত্তর সংরক্ষণ করা হয়নি।" : "No answer saved.")}</Text></View>} /><Pressable onPress={() => void deleteEntry(selected.id).then(() => setSelected(null))} style={({ pressed }) => [styles.delete, pressed && styles.pressed]}><Text style={styles.deleteText}>{tx("deleteEntry")}</Text></Pressable></> : null}</View></View></Modal></ScreenContainer>; }
const styles = StyleSheet.create({ screen: { backgroundColor: "#0B1020" }, content: { paddingBottom: 28, paddingHorizontal: 20, paddingTop: 18 }, kicker: { color: "#69D8E3", fontSize: 10, fontWeight: "900", letterSpacing: 1, marginTop: 23 }, title: { color: "#F4F7FB", fontSize: 33, fontWeight: "800", letterSpacing: -1, marginTop: 5 }, copy: { color: "#A7B3C9", fontSize: 15, lineHeight: 22, marginTop: 9 }, metrics: { flexDirection: "row", gap: 12, marginTop: 24 }, metric: { backgroundColor: "#151D33", borderColor: "#26334E", borderRadius: 18, borderWidth: 1, flex: 1, gap: 4, padding: 15 }, number: { color: "#F4F7FB", fontSize: 25, fontWeight: "800" }, metricLabel: { color: "#8290AB", fontSize: 10, fontWeight: "800", letterSpacing: 0.6 }, section: { color: "#F4F7FB", fontSize: 18, fontWeight: "800", marginBottom: 12, marginTop: 31 }, empty: { alignItems: "center", backgroundColor: "#10192D", borderColor: "#24324D", borderRadius: 20, borderStyle: "dashed", borderWidth: 1, gap: 8, padding: 26 }, emptyTitle: { color: "#E9EFF9", fontSize: 15, fontWeight: "800" }, emptyCopy: { color: "#94A2BA", fontSize: 13, lineHeight: 19, maxWidth: 260, textAlign: "center" }, backdrop: { backgroundColor: "rgba(4, 7, 16, 0.72)", flex: 1, justifyContent: "flex-end" }, sheet: { backgroundColor: "#10182B", borderTopColor: "#2C3A58", borderTopLeftRadius: 30, borderTopRightRadius: 30, borderTopWidth: 1, height: "72%", paddingBottom: 20, paddingHorizontal: 20 }, handle: { alignSelf: "center", backgroundColor: "#44516A", borderRadius: 10, height: 4, marginVertical: 11, width: 42 }, header: { alignItems: "flex-start", flexDirection: "row", justifyContent: "space-between" }, mode: { fontSize: 11, fontWeight: "900", letterSpacing: 1.1 }, sheetTitle: { color: "#F4F7FB", fontSize: 23, fontWeight: "800", marginTop: 4 }, close: { alignItems: "center", backgroundColor: "#202B43", borderRadius: 18, height: 36, justifyContent: "center", width: 36 }, closeText: { color: "#C5D0E0", fontSize: 24, lineHeight: 26 }, thought: { color: "#A7B3C9", fontSize: 15, lineHeight: 22, marginTop: 14 }, answers: { flex: 1 }, answerContent: { gap: 11, paddingBottom: 12, paddingTop: 20 }, answer: { backgroundColor: "#151D33", borderColor: "#26334E", borderRadius: 16, borderWidth: 1, gap: 6, padding: 14 }, prompt: { color: "#D2DEED", fontSize: 13, fontWeight: "800", lineHeight: 18 }, response: { color: "#96A4BA", fontSize: 13, lineHeight: 19 }, delete: { alignItems: "center", borderColor: "#7E3646", borderRadius: 14, borderWidth: 1, justifyContent: "center", minHeight: 48 }, deleteText: { color: "#FF9AA5", fontSize: 14, fontWeight: "900" }, pressed: { opacity: 0.7 } });
